### ISSUE TITLE
Design a LOGO for the mobile application

### ISSUE THREAD

**Issue by AsithaIndrajith** [scorelab/elly#7]
### Problem
**Elly** App is a new mobile app which is capable of spotting elephants for elephant conservation purposes. Since the targeted group of this app is normal users app need to have good logo. And the **solution is to design a user attractive logo** for the app.

### Existing logo
<img src="https://user-images.githubusercontent.com/25387297/71233183-c174ca80-231a-11ea-87ca-1fb354b6ef81.png" alt="Elly" title="existing elly logo" width="150" height="100" />

### Logo requirements
Can use any logo design tool.
Logo should be simple and effective.
Required outputs should includes **.PNG and .SVG** and any other
Needed in both rounded and squared images

### In pixels, the sizes are:
48 × 48 (mdpi) , with 1 dp padding.
72 × 72 (hdpi), with 1 dp padding.
96 × 96 (xhdpi), with 1 dp padding.
144 × 144 (xxhdpi), with 1 dp padding.
192 × 192 (xxxhdpi) , with 4 dp padding.

### Additional info
Sample screenshots of the mobile app. Link: **https://docs.google.com/document/d/1ZFEoA92RYztVIjW9fLxmG5eftYLrRZXGxA6q74FCJDI/edit?usp=sharing**

**Comment by SharmaIND** [comment]
Logo by Sharma IND. 
![poster1_1_203852](https://user-images.githubusercontent.com/59284021/71650896-6346df00-2d3f-11ea-9696-99abd2d75748.png)

**Comment by shivansh203** [comment]
![20200116_184651](https://user-images.githubusercontent.com/59904433/72528588-6f7b8200-3891-11ea-96ec-580d7f26b6b8.png)

My submission sir
Royal Shiv

**Comment by shivansh203** [comment]
![elly](https://user-images.githubusercontent.com/59904433/72531138-e0716880-3896-11ea-9f5d-444cbcdec0b9.png)

My updated submission sir
Royal Shiv

**Comment by ProCodec** [comment]
My logo
![final icon](https://user-images.githubusercontent.com/60006102/72667757-469bee00-3a45-11ea-9585-abe8f5513519.jpg)
-CodecOnline

**Comment by reubensabu47** [comment]
![elephant logo elly gradient](https://user-images.githubusercontent.com/59964472/72669660-b8326700-3a5a-11ea-9f7e-7829d889f4df.png)

-reubensabu47

**Comment by reubensabu47** [comment]
![elephant logo for elly app](https://user-images.githubusercontent.com/59964472/72669704-3f7fda80-3a5b-11ea-9076-cc6828bc5522.png)
- reubensabu47

**Comment by Vickykr1347** [comment]
![ele](https://user-images.githubusercontent.com/60095146/72720841-d2765d00-3ba0-11ea-9415-631490e23f2d.jpg)

**Comment by Vickykr1347** [comment]
Vicky kumar
